
# This is a basic workflow to help you get started with Actions
name: fetching algo problems
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch

on:
  schedule:
    # 오전 7시
    - cron: "0 12 * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: createIssue
        run: |
          npm ci
          npm run fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
   
